Update SendWA

diff --git a/SendWA b/SendWA
--- a/SendWA
+++ b/SendWA
@@ -1,10 +1,18 @@
 #!/bin/sh
 # shellcheck disable=SC2183,SC2030,SC2086,SC2181,SC2031
-currentVersion="v1.0"; rev_date="2 Jan 2023"; mp="$HOME/.sendwa"
+currentVersion="v1.0"; rev_date="2 Jan 2023"; mp="$HOME/.sendwa"; envfile="$mp/file.env"
 # Required Function
 is_installed() { command -v $1 >/dev/null 2>&1; }
 say () { printf "${cyan}%s${creset}" "$@"; }
 sayp() { printf "${cyan}%s${creset}\n" "$@"; }
+logger() {
+  date_bracket=$(date +"[%D %T]")
+  printf "%b\n" "${clyl}$date_bracket ${csky}$*${creset}"
+}
+dogger() {
+  date_bracket=$(date +"[%D %T]")
+  printf "%b\n" "${clyl}$date_bracket ${cred}$*${creset}" >&2
+}
 die() { printf "${cred}%s${creset}" "$@" >&2; }
 diep() { printf "${cred}%s${creset}\n" "$@" >&2; }
 cleanup() {
@@ -98,7 +106,7 @@ display_help() {
   -v, --version           Display version
 EOT
 }
-usage_error () { printf "%s\n%s\n" "$1" "Try 'washell --help' to view available option" >&2; exit 2; }
+usage_error () { printf "%s\n%s\n" "$1" "Try 'sendwa --help' to view available option" >&2; exit 2; }
 assert_argument () { { test "$1" != "$endofline" && case "$1" in -*) >&2 printf "%s\n" "$opt: Illegal input parameter ($1)"; exit 2;; esac; } || { printf "%s\n" "$2: requires an argument" >&2 && exit 2 ; }; }
 endofline=$(printf '\1\3\3\7')
 if [ "$#" != 0 ]; then
@@ -107,10 +115,10 @@ if [ "$#" != 0 ]; then
     opt="$1"; shift
     case "$opt" in
       --install) install && exit 0;;
+      --uninstall) uninstall && exit 0;;
       -o|--number)
       assert_argument "$1" "$opt"
       phonelist="$1"
-      formphone
       shift
       ;;
       -t|--text)
@@ -133,36 +141,44 @@ fi
 # END OPTION PARSING
 # Main components
 formphone() {
-  randstring=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1)
-  randfile="$mp/numlist_${randstring}.txt"
+  sendthisjson="$mp/temporary.json"; echo "[]" > $sendthisjson
   case "$phonelist" in
     *,*)
     phonelist=$(echo "$phonelist" | tr -d '[:space:]' | tr ',' ' ')
     for phone in $phonelist; do
       if [ -z "${phone##*[!0-9]*}" ]; then
-        die "$phone must be valid number"; exit 1
+        die "$phone must be valid number"; continue
       else
-        printf %s "$phone" > $randfile # Crowdnumber
+        $jq --arg phony "$phone" --arg thetext "$text" \
+        '. += [{"recipient_type":"individual","to":"\($phony)","type":"text","text":{"body": "\($thetext)"}}]' $sendthisjson > /tmp/temp.json && mv /tmp/temp.json $sendthisjson
       fi
     done
       ;;
     *)
     if [ -z "${phonelist##*[!0-9]*}" ]; then
-      die "$phonelist must be valid number"; exit 1
+      die "$phonelist must be valid number"; continue
     else
-      printf %s "$phonelist" > $randfile # Crowdnumber
+      $jq --arg phony "$phonelist" --arg thetext "$text" \
+      '. += [{"recipient_type":"individual","to":"\($phony)","type":"text","text":{"body": "\($thetext)"}}]' $sendthisjson > /tmp/temp.json && mv /tmp/temp.json $sendthisjson
     fi
       ;;
   esac
 }
 send() {
   if [ "$filegrab" = "c" ]; then
-    # Nomor Telepon
-    _notel="$1"
-    _text="$2"
-    curl --location
+    _httpcode=$(
+    curl -w "%{http_code}" -s -o /dev/null \
+    --location --request POST "$WA_API_URL" \
+    --header "Authorization: Bearer ${WA_API_KEY}" \
+    --data-binary "@${sendthisjson}"
+    )
+    if [ "_$_httpcode" = 200 ]; then logger "Successfully sent message !"; else dogger "Request failed to get through !"; return 1; fi
   elif [ "$filegrab" = "w" ]; then
-    #statements
+    wget --no-check-certificate -qO /dev/null \
+    --method POST --timeout=0 \
+    --header "Authorization: Bearer ${WA_API_KEY}" \
+    --body-file="${sendthisjson}" "$WA_API_URL"
+    if [ $? -eq 0 ]; then logger "Successfully sent message !"; else dogger "Request failed to get through !"; return 1; fi
   fi
 }
 send_test() {
@@ -211,16 +227,23 @@ install() {
   send_test
   if [ $? -eq 0 ]; then printf "${cgreen}%s${creset}\n" " [SUCCESS]"; else diep " [FAIL]" && exit 1; fi
   # Putting api config to env file
-  cat <<EOF > $mp/sendwa.env
+  cat <<EOF > $envfile
 # DO NOT REMOVE THIS FILE UNDER ANY CIRCUMSTANCE
-WA_API="$wa_api_key"
-WA_URL="$wa_api_url"
+WA_API_KEY="$wa_api_key"
+WA_API_URL="$wa_api_url"
 EOF
   # Closing
   say 'SendWA has been installed, invoke this script with `sendwa [option]`'
   sayp "This script will auto delete in 2 secs"; sleep 2; rm -f -- "$0"
 }
+uninstall() {
+  say "Removing $mp"
+  rm -r -- "$mp"
+  printf "${cgreen}%s${creset}\n" " [SUCCESS]"
+}
 main() {
-
+  [ -f "$envfile" ] && . $envfile
+  formphone
+  send
 }
 main
